id: 0b24df05071448a3b9788bcc26527a5b
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_163-Questions_of_Ratnaj%C4%81lin-v2
  language: bo
  author: ''
  volume: {}
